version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - GO_ENV=development
      - MONGO_URL = mongodb+srv://piyush1:MNi0Frou2R3gFWFN@cluster0.zzkbr72.mongodb.net/
    command: air
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
