name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file with secrets
        run: |
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
            chmod 600 .env # Restrict permissions

      - name: Set up SSH key
        run: |
            echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/dev_key.pem
            chmod 600 /tmp/dev_key.pem # Restrict permissions to the private key
    
      - name: Copy files to EC2 using SCP
        run: |
            scp -o StrictHostKeyChecking=no -i /tmp/dev_key.pem -r ./ ubuntu@${{ secrets.EC2_IP_ADDRESS }}:/home/ubuntu/app
    
      - name: Run Docker Compose on EC2
        run: |
            ssh -o StrictHostKeyChecking=no -i /tmp/dev_key.pem ubuntu@${{ secrets.ADDRESS }} << 'EOF'
            cd /home/ubuntu/app
            docker-compose down --remove-orphans
            docker-compose up -d --build
            EOF