name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file with secrets
        run: |
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
            chmod 600 .env # Restrict permissions