name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file with secrets
        run: |
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
            chmod 600 .env # Restrict permissions

      - name: Set up SSH key
        run: |
            echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/dev_key.pem
            chmod 600 /tmp/dev_key.pem # Restrict permissions to the private key\
      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH Connection to EC2
        run: |
            ssh -o StrictHostKeyChecking=no -i /tmp/dev_key.pem ubuntu@${{ secrets.EC2_IP_ADDRESS }} "hostname"
    
      - name: SSH into EC2 and pull code from GitHub
        run: |
            ssh -o StrictHostKeyChecking=no -i /tmp/dev_key.pem ubuntu@${{ secrets.EC2_IP_ADDRESS }} << 'EOF'
            # Change to the app directory or clone the repo if it doesn't exist
            if [ ! -d "/home/ubuntu/app" ]; then
              git clone ${{ secrets.REPOSITORY }} /home/ubuntu/app
            fi
            cd /home/ubuntu/app
            echo "pulling code"
            git pull origin main
            docker-compose down --remove-orphans
            docker-compose up -d --build
            EOF