name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file with secrets
        run: |
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
            chmod 600 .env # Restrict permissions

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
         ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
    
          # Step 3: Copy files to the EC2 instance using SCP
      - name: Copy files to EC2
        run: |
            scp -o StrictHostKeyChecking=no -r ./ ubuntu@${{ secrets.ADDRESS }}:/home/ubuntu/app

        # Step 4: SSH into EC2 and run Docker Compose
      - name: Run Docker Compose on EC2
        run: |
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.ADDRESS }} << 'EOF'
            cd /home/ubuntu/app
            docker-compose down --remove-orphans
            docker-compose up -d --build
            EOF