name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env file with secrets
        run: |
            echo "MONGO_URL=${{ secrets.MONGO_URL }}" > .env
            chmod 600 .env # Restrict permissions

      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.DEV_CONNECT }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
    
          # Step 3: Copy files to the EC2 instance using SCP
      - name: Copy files to EC2
        run: |
            scp -o StrictHostKeyChecking=no -r ./ ec2-user@${{ secrets.ADDRESS }}:/home/ec2-user/app

        # Step 4: SSH into EC2 and run Docker Compose
      - name: Run Docker Compose on EC2
        run: |
            ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.ADDRESS }} << 'EOF'
            cd /home/ec2-user/app
            docker-compose down --remove-orphans
            docker-compose up -d --build
            EOF